### ISSUE TITLE
Make favicon

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#9]

**Comment by Sky-De** [comment]
@miljkovicjovan  assign this to me please
thanks

**Comment by miljkovicjovan** [comment]
@Sky-De sorry this issue will be finished by me when I create a design for the favicon. Thanks for your contributions you can choose another issue or open a new one to work on.

**Comment by Sky-De** [comment]
@miljkovicjovan I see, it is ok
but I've finished that
take a look at this  favicon mtt short hand for your app name 
if you like this let me know to make a pull request 
otherwise feel free to use your own design
![Screenshot 2023-10-31 030150](https://github.com/miljkovicjovan/minimalist-task-tracker/assets/79264045/6699b68a-812d-41b8-950c-2fa8dd59cd0d)


thanks

**Comment by miljkovicjovan** [comment]
@Sky-De You can make a PR and we will use it for now until I create a new one, thank you.

**Comment by Sky-De** [comment]
@miljkovicjovan  it sounds good for me 
thanks
